version: ' 3 '


services:
  mongodb:
    container_name: mongodb
    image: reemboww-mongodb_live_app:1.0.0
    build: .
    ports:
      - "3000"
    environment:
      - DB_URL = mongodb+srv://khaledshaaban926:26EzpMouMmo4bXFC@cluster0.iwjiarl.mongodb.net/test
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: postgres:12
    ports:
      - "3000"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
    